# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "efficient-shipping-app"
client_id = "940532dbc9a941e979e03887754d6cf2"
application_url = "https://effort-bald-productivity-man.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_files,write_files,read_content,write_content"

[auth]
redirect_urls = [
  "https://effort-bald-productivity-man.trycloudflare.com/auth/callback",
  "https://effort-bald-productivity-man.trycloudflare.com/auth/shopify/callback",
  "https://effort-bald-productivity-man.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testaccesstoken.myshopify.com"
